project:
  name: start
spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: xport
      username: xport
      password: xport
management:
  health:
    mongo:
      enabled: false